#
# Makefile.Config
#
# This file contains various configuration information.
#

#
# OS setup:
#
OS        := darwin12.5.0
ARCH      := i386

SHELL   := /bin/sh

#
# global compiler settings
#

ifndef SAC2C
SAC2C = sac2c
endif

ifneq ($(CROSS),)
  CROSS_TARGET     := -target $(CROSS)
  CROSS_VARIANT    := $(shell $(SAC2C) $(CROSS_TARGET) -CLIB_VARIANT)
  CC               := $(shell $(SAC2C) $(CROSS_TARGET) -CCC)
override  CCFLAGS  += $(shell $(SAC2C) $(CROSS_TARGET) -CCCFLAGS)
  AR               := $(shell $(SAC2C) $(CROSS_TARGET) -CAR_CREATE)
  RANLIB           := $(shell $(SAC2C) $(CROSS_TARGET) -CRANLIB)
  BACKEND          := $(shell $(SAC2C) $(CROSS_TARGET) -CBACKEND)
  CROSS_FOR        := for $(CROSS_VARIANT)

override  SAC2CFLAGS += $(CROSS_TARGET)

else
  CC      := gcc
override  CCFLAGS += -Wall -std=c99
  AR = ar
  ARFLAGS = 
  RANLIB = ranlib -c
  BACKEND          := $(shell $(SAC2C) -CBACKEND)
endif

override CCFLAGS += -DCHECK -DHAVE_PUTENV -D__EXTENSIONS__
override CCFLAGS += -DSAC_RC_METHOD=SAC_RCM_$(shell $(SAC2C) $(CROSS_TARGET) -CRC_METHOD)

#
# enable or disable PHM
#
LIB_PHM := 

#
# set whether to link extra math lib
#
LIB_M   := -lm

#
# set specific compiler flags
#
override CCFLAGS += -Wall -std=c99 
LDFLAGS := -Wl,-multiply_defined,suppress $(LDFLAGS)


ifndef SAC2TEX
SAC2TEX = sac2tex
endif


#
# unless stated otherwise, make non-local dependencies for non stdlib only!
#
ifndef SAC2CMLIB
SAC2CMLIB = -M
endif

TAR = tar
LEX = flex
LFLAGS = -P$(*F)
YACC = bison
YFLAGS = -d -v -p $(*F)

LATEX = latex

DVIPS = dvips

LATEX2HTML = latex2html
LATEX2HTMLFLAGS = -info 0 -html_version 3.2

FIGPS = fig2dev -Leps
FIGPSFLAGS = -c -b0

FIGGIF = fig2dev -Lgif
FIGGIFFLAGS = -m0.7 -b20 -t0

FIGPNG = fig2dev -Lpng
FIGPNGFLAGS = -m0.7 -b20

AWK           = awk
NAWK          = awk

ENABLE_PNG     := no
ENABLE_JPEG    := no
ENABLE_SDL     := 
ENABLE_DISLIN  := 
ENABLE_RTCLOCK := yes
ENABLE_GNUPLOT := no
GNUPLOT_PATH   := 
ENABLE_MUTC    := no
SLC_PATH       := 
SDLCFLAGS      := 
SDLLIBS        := 

LS            = ls
LN            = ln -s
CD            = cd
RM            = rm -rf
CAT           = cat
MKDIR         = mkdir -p
RMDIR         = rmdir
DIFF          = diff
MV            = mv -f
TOUCH         = touch
DATE          = date +%d.%b.%y
DATE_TIME     = date
ZIP           = gzip -f
UNZIP         = gunzip -f
NOOP          = sleep 1

UUENCODE      = uuencode
UUDECODE      = uudecode

ifndef MEASURE
MEASURE       = timemult -i -h $(HOSTMACHINE) -l $(HOSTLOGIN) -r 4
# MEASURE       = time
endif

ifndef HOSTMACHINE
HOSTMACHINE   = $(HOST)
endif

ifndef HOSTLOGIN
HOSTLOGIN     = $(USER)
endif


ECHO                   = $(SAC2CBASE)/src/bin/echo -e $(INDENT)
CLOCK_SKEW_ELIMINATION = $(SAC2CBASE)/src/bin/cse



DECDIR := $(SACBASE)/stdlib/modules/structures  \
          $(SACBASE)/stdlib/modules/numerical  \
          $(SACBASE)/stdlib/modules/auxiliary  \
          $(SACBASE)/stdlib/modules/mutc  \
          $(SACBASE)/stdlib/classes/random  \
          $(SACBASE)/stdlib/world/system  \
          $(SACBASE)/stdlib/world/stdio  \
          $(SACBASE)/stdlib/world/x-window  \
          $(SACBASE)/stdlib/hidden

LIBDIR := $(addsuffix /lib, $(DECDIR))

CCINCLUDEDIR := $(SAC2CBASE)/include

#
# include optional local overrides
#
-include $(SACBASE)/stdlib/Makefiles/Makefile.LocalSettings

#
# Set the shared library file suffix 
#

SHARED_LIB_EXT  := .so

