#
# Makefile.Config
#
# This file contains various configuration information.
#

#
# OS setup:
#
OS        := `uname -s`
OSREV     := `uname -r`
ARCH      := `arch`

SHELL   := /bin/sh

#
# global compiler settings
#

ifndef SAC2C
SAC2C = sac2c
endif

#
# set specific compiler flags
#
override CCFLAGS += -Wall -std=c99 
LDFLAGS := -Wl,-multiply_defined,suppress $(LDFLAGS)



ECHO          = echo
NAWK          = awk
LS            = ls
LN            = ln -s
CD            = cd
RM            = rm -rf
CAT           = cat
MKDIR         = mkdir -p
RMDIR         = rmdir
DIFF          = diff
MV            = mv -f
TOUCH         = touch
DATE          = date +%d.%b.%y
DATE_TIME     = date
ZIP           = gzip -f
UNZIP         = gunzip -f
NOOP          = sleep 1

UUENCODE      = uuencode
UUDECODE      = uudecode

ifndef MEASURE
MEASURE       = timemult -i -h $(HOSTMACHINE) -l $(HOSTLOGIN) -r 4
# MEASURE       = time
endif

ifndef HOSTMACHINE
HOSTMACHINE   = $(HOST)
endif

ifndef HOSTLOGIN
HOSTLOGIN     = $(USER)
endif


ifeq ( $OS), Darwin)
SHARED_LIB_EXT  := .so
else
SHARED_LIB_EXT  := .dylib
endif
